"""Module: Ontology subpackage (frozen v0.1) | Paper section: §2 | Status: frozen"""

from ssp.ontology.entities import (
    EntityType,
    PhysicalObjectSubtype,
    Vulnerability,
    ZoneType,
)
from ssp.ontology.relations import (
    PROPAGATION_RELATIONS,
    SUPPRESSION_RELATIONS,
    L0Relation,
    L1PropagationRelation,
    L1SuppressionRelation,
)
from ssp.ontology.risk_events import (
    ActionActivator,
    ActivationCondition,
    ActivationRule,
    EntityFilter,
    InstantiationCondition,
    MitigationSpec,
    PropagationEdgeSpec,
    RiskEventTemplate,
    RiskEventType,
)
from ssp.ontology.schema import (
    ActionKinematics,
    ActionParticipant,
    AttentionState,
    CandidateAction,
    ContainmentState,
    Edge,
    EnergyState,
    FactorNode,
    MotionState,
    Node,
    OrientationState,
    PoseState,
    RiskVector,
    StabilityState,
    StateSchema,
    UncertaintyTag,
    UncertaintyVector,
)

__all__ = [
    "ActionActivator",
    "ActionKinematics",
    "ActionParticipant",
    "ActivationCondition",
    "ActivationRule",
    "AttentionState",
    "CandidateAction",
    "ContainmentState",
    "Edge",
    "EnergyState",
    "EntityFilter",
    "EntityType",
    "FactorNode",
    "InstantiationCondition",
    "L0Relation",
    "L1PropagationRelation",
    "L1SuppressionRelation",
    "MitigationSpec",
    "MotionState",
    "Node",
    "OrientationState",
    "PROPAGATION_RELATIONS",
    "PhysicalObjectSubtype",
    "PoseState",
    "PropagationEdgeSpec",
    "RiskEventTemplate",
    "RiskEventType",
    "RiskVector",
    "SUPPRESSION_RELATIONS",
    "StabilityState",
    "StateSchema",
    "UncertaintyTag",
    "UncertaintyVector",
    "Vulnerability",
    "ZoneType",
]
